config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    get "tasks", to: "tasks#index"

    get    "tasks/new",      to: "tasks#new"
    post   "tasks",          to: "tasks#create"

    get "tasks/:id", to: "tasks#show", as: :task


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end


  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    # Will raise ActiveModel::ForbiddenAttributesError
    redirect_to task_path(@task)

  end

  private

  def task_params
    # *Strong params*: You need to *whitelist* what can be updated by the user
    # Never trust user data!
    params.require(:task).permit(:title, :details)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Reminders</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/index.html.erb
<h1>Reminders</h1>
<ul>
  <% @tasks.each do |task| %>
    <li><%= task[:completed] ? '☑' : '□' %> <%= link_to task.title, task_path(task) %></li>
  <% end %>
</ul>
<%= link_to '+ New errand', tasks_new_path %>

app/views/tasks/new.html.erb
<h1>New errand</h1>
<%= form_for(@task) do |f| %>
  <%= f.label :title %>
  <p><%= f.text_field :title %></p>

  <%= f.label :details %>
  <p><%= f.text_area :details %></p>

  <%= f.submit %>
<% end %>
<p><%= link_to 'Home', tasks_path %></p>

app/views/tasks/show.html.erb
<h1><%= @task[:title] %></h1>
<p><%= @task[:details] %></p>
<%= link_to "Home", tasks_path %>